/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coponieve;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author danny
 */
public class Interfaz extends javax.swing.JFrame {
    Graphics g;
    public int iteraciones;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        this.iteraciones=0;
        initComponents();
        g = this.getGraphics();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        NumIte = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Copo de nieve (Curva de Koch)");
        setPreferredSize(new java.awt.Dimension(600, 600));

        jButton1.setText("Dibujar / Redibujar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NumIte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6" }));
        NumIte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NumIteItemStateChanged(evt);
            }
        });

        jLabel1.setText("Numero de Iteraciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumIte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(NumIte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumIteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NumIteItemStateChanged
        // TODO add your handling code here:
        if(evt.getSource()==NumIte){
            String valor =(String)NumIte.getSelectedItem();
            int num = Integer.parseInt(valor);
            this.iteraciones=num;
        }
    }//GEN-LAST:event_NumIteItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        update(g);
        double sin60=Math.sin(3.14/3.);
        CurvasKoch copo = new CurvasKoch();
        int x1 = 100;
        int y1 = 450;
        int x2 = 500;
        int y2 = 450;
        
        double dx=(x2-x1)/2.;
        double dy=(y2-y1)/2.;
        double x3=x1+dx+2*dy*sin60;
        double y3=y1+dy-2*dx*sin60;
        
        g.setColor(Color.blue);
        copo.dibujarCurva(g, this.iteraciones, x1, y1, x2, y2);
        copo.dibujarCurva(g, this.iteraciones, x3, y3, x1, y1);
        copo.dibujarCurva(g, this.iteraciones, x2, y2, x3, y3);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> NumIte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
