/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegovida;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author danny
 */
public class Tablero extends javax.swing.JFrame {
    private Juego game;
    private Graphics g;
    public Tablero() {
        initComponents();
        g = this.panelT.getGraphics(); 
        this.back.setVisible(false);
        this.next.setVisible(false);
        
    }
    
    private void esconderFlechas(){
        
        if(this.game.turno == 0){
            this.back.setVisible(false);
            this.next.setVisible(true);
        }else{
            this.back.setVisible(true);
            this.next.setVisible(true);
        }
    }
    
    public void tableroActualizar(int [][] tab){
        this.panelT.update(g);
         for (int i = 0; i < 50; i++) {
            for (int j = 0; j < 50; j++) {
                if(tab[i][j]==1){
                    int auxI=10*(i+1)-10;
                    int auxJ=10*(j+1)-10;
                    //g.setColor(new Color((int)(Math.random()*250 + 1), (int)(Math.random()*250 + 1), (int)(Math.random()*250 + 1)));
                    g.fillRect(auxI, auxJ, 10, 10);
                }
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonEmpezar = new javax.swing.JButton();
        panelT = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        labelTurno = new javax.swing.JLabel();
        labelCel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de la vida\n");
        setResizable(false);

        botonEmpezar.setText("Nuevo Juego");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        panelT.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout panelTLayout = new javax.swing.GroupLayout(panelT);
        panelT.setLayout(panelTLayout);
        panelTLayout.setHorizontalGroup(
            panelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        panelTLayout.setVerticalGroup(
            panelTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        next.setText(">");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        back.setText("<");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        labelTurno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTurno.setText("Turno: 0");

        labelCel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCel.setText("Celulas vivas: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonEmpezar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelTurno)
                        .addGap(18, 18, 18)
                        .addComponent(labelCel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(next)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEmpezar)
                    .addComponent(next)
                    .addComponent(back)
                    .addComponent(labelTurno)
                    .addComponent(labelCel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        // TODO add your handling code here:
        game = new Juego();
        this.tableroActualizar(this.game.matrizTablero);
        this.labelCel.setText("Celulas vivas: " + this.game.celulasVivas);
        esconderFlechas();
    }//GEN-LAST:event_botonEmpezarActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        this.game.sigTurno();
        this.tableroActualizar(this.game.matrizTablero);
        this.labelTurno.setText("Turno: " + this.game.turno);
        this.labelCel.setText("Celulas vivas: " + this.game.celulasVivas);
        esconderFlechas();
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.game.antTurno();
        this.tableroActualizar(this.game.matrizTablero);
        this.labelTurno.setText("Turno: " + this.game.turno);
        this.labelCel.setText("Celulas vivas: " + this.game.celulasVivas);
        esconderFlechas();
    }//GEN-LAST:event_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JLabel labelCel;
    private javax.swing.JLabel labelTurno;
    private javax.swing.JButton next;
    private javax.swing.JPanel panelT;
    // End of variables declaration//GEN-END:variables
}
